name: Auto Deploy to EasyPanel

on:
  push:
    branches:
      - main  # Solo deploya cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Trigger EasyPanel Deploy
        run: |
          curl -X POST http://76.13.148.149:3000/api/deploy/972b0a644ce69f5b784d85dc99e01bece8aec5a8bd4e547e
