name: Auto Deploy to EasyPanel

on:
  push:
    branches:
      - main  # Solo deploya cuando hagas push a main

jobs:
  deploy:
    runs-on: ubuntu-latest
 
    steps:
      - name: Trigger EasyPanel Deploy
        run: |
          curl -X POST http://206.183.130.17:3000/api/deploy/8f31ebb38d03cc13c244b082175dc901fb662f2897ea8bb3
